#!/usr/bin/env bash

export CONTECO_LABEL="package.ingest - ModEco"
export CONTECO_DESCRIPTION="The ingest module package."

export CONTECO_TYPE="package"
export CONTECO_NAME="ingest_file"
export CONTECO_TAG="7.9.2"


export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="modeco"
