#!/usr/bin/env bash


prefix="package_$2"


executionplane --silent docker container prune --force

if [[ "package_ingest_filebeat_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume rm --force package_ingest_filebeat_volume
	fi
	
